# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpcCalc_pb2 as grpcCalc__pb2


class apiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/main.api/add',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                )
        self.sub = channel.unary_unary(
                '/main.api/sub',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                )
        self.mul = channel.unary_unary(
                '/main.api/mul',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                )
        self.div = channel.unary_unary(
                '/main.api/div',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                )


class apiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mul(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def div(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'sub': grpc.unary_unary_rpc_method_handler(
                    servicer.sub,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'mul': grpc.unary_unary_rpc_method_handler(
                    servicer.mul,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'div': grpc.unary_unary_rpc_method_handler(
                    servicer.div,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.api/add',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.api/sub',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def mul(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.api/mul',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.api/div',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
